# Generated by Django 5.2 on 2025-04-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('mensa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(to='mensa.dish'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suffers_from',
            field=models.ManyToManyField(to='mensa.allergen'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='economical_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.economicallevel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.university'),
        ),
    ]
