# Generated by Django 5.2 on 2025-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_economical_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='propic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
