# Generated by Django 5.2 on 2025-04-23 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('landscape', models.ImageField(upload_to='landscapes/')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(unique=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='dish-photos/')),
                ('allergens', models.ManyToManyField(to='mensa.allergen')),
                ('ingredients', models.ManyToManyField(to='mensa.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='events/')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('name', 'date'), name='unique_name_date')],
            },
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(2, 'Contorno'), (1, 'Secondo'), (0, 'Primo'), (3, 'Dessert/Frutta')])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Mensa',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('position', models.CharField(max_length=255)),
                ('banner', models.ImageField(upload_to='banners/')),
                ('capacity', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mensa.city')),
                ('gallery', models.ManyToManyField(to='mensa.photomensa')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(4, 'Venerdi'), (1, 'Martedi'), (0, 'Lunedi'), (2, 'Mercoledi'), (3, 'Giovedi'), (6, 'Domenica'), (5, 'Sabato')])),
                ('day_part', models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')])),
                ('dishes', models.ManyToManyField(through='mensa.Includes', to='mensa.dish')),
                ('mensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa')),
            ],
            options={
                'ordering': ['weekday', 'day_part'],
            },
        ),
        migrations.AddField(
            model_name='includes',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.menu'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('text', models.TextField(blank=True, null=True)),
                ('mensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(4, 'Venerdi'), (1, 'Martedi'), (0, 'Lunedi'), (2, 'Mercoledi'), (3, 'Giovedi'), (6, 'Domenica'), (5, 'Sabato')])),
                ('daypart', models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('mensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.mensa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mensa', 'weekday', 'daypart'), name='hours_unique_mensa_weekday_daypart')],
            },
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('mensa', 'weekday', 'day_part'), name='menu_unique_mensa_weekday_daypart'),
        ),
        migrations.AddConstraint(
            model_name='includes',
            constraint=models.UniqueConstraint(fields=('menu', 'dish'), name='unique_menu_dish'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('mensa', 'user'), name='unique_mensa_user_review'),
        ),
    ]
