# Generated by Django 5.2 on 2025-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
