# Generated by Django 5.2 on 2025-04-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='daypart',
            field=models.IntegerField(choices=[(0, 'Pranzo'), (1, 'Cena')]),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(4, 'Venerdi'), (6, 'Domenica'), (2, 'Mercoledi'), (1, 'Martedi'), (0, 'Lunedi'), (3, 'Giovedi'), (5, 'Sabato')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(0, 'Primo'), (3, 'Dessert/Frutta'), (2, 'Contorno'), (1, 'Secondo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_part',
            field=models.IntegerField(choices=[(0, 'Pranzo'), (1, 'Cena')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(4, 'Venerdi'), (6, 'Domenica'), (2, 'Mercoledi'), (1, 'Martedi'), (0, 'Lunedi'), (3, 'Giovedi'), (5, 'Sabato')]),
        ),
    ]
