# Generated by Django 5.2 on 2025-04-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0002_alter_hours_daypart_alter_hours_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(6, 'Domenica'), (1, 'Martedi'), (3, 'Giovedi'), (0, 'Lunedi'), (5, 'Sabato'), (4, 'Venerdi'), (2, 'Mercoledi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(1, 'Secondo'), (3, 'Dessert/Frutta'), (0, 'Primo'), (2, 'Contorno')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(6, 'Domenica'), (1, 'Martedi'), (3, 'Giovedi'), (0, 'Lunedi'), (5, 'Sabato'), (4, 'Venerdi'), (2, 'Mercoledi')]),
        ),
    ]
