# Generated by Django 5.2 on 2025-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0003_alter_hours_weekday_alter_includes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='daypart',
            field=models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')]),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lunedi'), (1, 'Martedi'), (2, 'Mercoledi'), (4, 'Venerdi'), (5, 'Sabato'), (6, 'Domenica'), (3, 'Giovedi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(2, 'Contorno'), (0, 'Primo'), (3, 'Dessert/Frutta'), (1, 'Secondo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_part',
            field=models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lunedi'), (1, 'Martedi'), (2, 'Mercoledi'), (4, 'Venerdi'), (5, 'Sabato'), (6, 'Domenica'), (3, 'Giovedi')]),
        ),
    ]
