# Generated by Django 5.2 on 2025-05-19 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0004_alter_hours_daypart_alter_hours_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='allergen-icons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(5, 'Sabato'), (1, 'Martedi'), (4, 'Venerdi'), (3, 'Giovedi'), (6, 'Domenica'), (0, 'Lunedi'), (2, 'Mercoledi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(1, 'Secondo'), (3, 'Dessert/Frutta'), (2, 'Contorno'), (0, 'Primo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(5, 'Sabato'), (1, 'Martedi'), (4, 'Venerdi'), (3, 'Giovedi'), (6, 'Domenica'), (0, 'Lunedi'), (2, 'Mercoledi')]),
        ),
    ]
