# Generated by Django 5.2 on 2025-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0005_allergen_icon_city_latitude_city_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensa',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensa',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hours',
            name='daypart',
            field=models.IntegerField(choices=[(0, 'Pranzo'), (1, 'Cena')]),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Martedi'), (0, 'Lunedi'), (5, 'Sabato'), (4, 'Venerdi'), (3, 'Giovedi'), (2, 'Mercoledi'), (6, 'Domenica')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(3, 'Dessert/Frutta'), (2, 'Contorno'), (0, 'Primo'), (1, 'Secondo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_part',
            field=models.IntegerField(choices=[(0, 'Pranzo'), (1, 'Cena')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Martedi'), (0, 'Lunedi'), (5, 'Sabato'), (4, 'Venerdi'), (3, 'Giovedi'), (2, 'Mercoledi'), (6, 'Domenica')]),
        ),
    ]
