# Generated by Django 5.2 on 2025-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0006_mensa_latitude_mensa_longitude_alter_hours_daypart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Giovedi'), (4, 'Venerdi'), (5, 'Sabato'), (1, 'Martedi'), (2, 'Mercoledi'), (0, 'Lunedi'), (6, 'Domenica')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(3, 'Dessert/Frutta'), (0, 'Primo'), (2, 'Contorno'), (1, 'Secondo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Giovedi'), (4, 'Venerdi'), (5, 'Sabato'), (1, 'Martedi'), (2, 'Mercoledi'), (0, 'Lunedi'), (6, 'Domenica')]),
        ),
    ]
