# Generated by Django 5.2 on 2025-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0007_alter_hours_weekday_alter_includes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='daypart',
            field=models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')]),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(4, 'Venerdi'), (6, 'Domenica'), (1, 'Martedi'), (3, 'Giovedi'), (2, 'Mercoledi'), (0, 'Lunedi'), (5, 'Sabato')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(1, 'Secondo'), (0, 'Primo'), (2, 'Contorno'), (3, 'Dessert/Frutta')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_part',
            field=models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(4, 'Venerdi'), (6, 'Domenica'), (1, 'Martedi'), (3, 'Giovedi'), (2, 'Mercoledi'), (0, 'Lunedi'), (5, 'Sabato')]),
        ),
    ]
