# Generated by Django 5.2 on 2025-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0009_alter_city_options_alter_hours_daypart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='daypart',
            field=models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')]),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(6, 'Domenica'), (5, 'Sabato'), (1, 'Martedi'), (2, 'Mercoledi'), (3, 'Giovedi'), (0, 'Lunedi'), (4, 'Venerdi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(2, 'Contorno'), (3, 'Dessert/Frutta'), (0, 'Primo'), (1, 'Secondo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_part',
            field=models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(6, 'Domenica'), (5, 'Sabato'), (1, 'Martedi'), (2, 'Mercoledi'), (3, 'Giovedi'), (0, 'Lunedi'), (4, 'Venerdi')]),
        ),
    ]
