# Generated by Django 5.2 on 2025-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0010_alter_hours_daypart_alter_hours_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='daypart',
            field=models.IntegerField(choices=[(0, 'Pranzo'), (1, 'Cena')]),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(2, 'Mercoledi'), (0, 'Lunedi'), (6, 'Domenica'), (3, 'Giovedi'), (1, 'Martedi'), (4, 'Venerdi'), (5, 'Sabato')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(0, 'Primo'), (2, 'Contorno'), (3, 'Dessert/Frutta'), (1, 'Secondo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_part',
            field=models.IntegerField(choices=[(0, 'Pranzo'), (1, 'Cena')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(2, 'Mercoledi'), (0, 'Lunedi'), (6, 'Domenica'), (3, 'Giovedi'), (1, 'Martedi'), (4, 'Venerdi'), (5, 'Sabato')]),
        ),
    ]
