# Generated by Django 5.2.1 on 2025-05-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0011_alter_hours_daypart_alter_hours_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(2, 'Mercoledi'), (3, 'Giovedi'), (5, 'Sabato'), (6, 'Domenica'), (1, 'Martedi'), (4, 'Venerdi'), (0, 'Lunedi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(0, 'Primo'), (2, 'Contorno'), (1, 'Secondo'), (3, 'Dessert/Frutta')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(2, 'Mercoledi'), (3, 'Giovedi'), (5, 'Sabato'), (6, 'Domenica'), (1, 'Martedi'), (4, 'Venerdi'), (0, 'Lunedi')]),
        ),
    ]
