# Generated by Django 5.2.1 on 2025-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0012_alter_hours_weekday_alter_includes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Martedi'), (6, 'Domenica'), (3, 'Giovedi'), (2, 'Mercoledi'), (0, 'Lunedi'), (4, 'Venerdi'), (5, 'Sabato')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(2, 'Contorno'), (3, 'Dessert/Frutta'), (1, 'Secondo'), (0, 'Primo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Martedi'), (6, 'Domenica'), (3, 'Giovedi'), (2, 'Mercoledi'), (0, 'Lunedi'), (4, 'Venerdi'), (5, 'Sabato')]),
        ),
    ]
