# Generated by Django 5.2.1 on 2025-05-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0015_alter_hours_weekday_alter_includes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='daypart',
            field=models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')]),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(2, 'Mercoledi'), (5, 'Sabato'), (4, 'Venerdi'), (1, 'Martedi'), (6, 'Domenica'), (0, 'Lunedi'), (3, 'Giovedi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(0, 'Primo'), (1, 'Secondo'), (3, 'Dessert/Frutta'), (2, 'Contorno')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_part',
            field=models.IntegerField(choices=[(1, 'Cena'), (0, 'Pranzo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(2, 'Mercoledi'), (5, 'Sabato'), (4, 'Venerdi'), (1, 'Martedi'), (6, 'Domenica'), (0, 'Lunedi'), (3, 'Giovedi')]),
        ),
    ]
