# Generated by Django 5.2.1 on 2025-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0016_alter_hours_daypart_alter_hours_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Giovedi'), (1, 'Martedi'), (4, 'Venerdi'), (6, 'Domenica'), (5, 'Sabato'), (2, 'Mercoledi'), (0, 'Lunedi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(1, 'Secondo'), (3, 'Dessert/Frutta'), (2, 'Contorno'), (0, 'Primo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Giovedi'), (1, 'Martedi'), (4, 'Venerdi'), (6, 'Domenica'), (5, 'Sabato'), (2, 'Mercoledi'), (0, 'Lunedi')]),
        ),
    ]
