# Generated by Django 5.2 on 2025-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0016_alter_hours_daypart_alter_hours_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Giovedi'), (
                4, 'Venerdi'), (1, 'Martedi'), (0, 'Lunedi'), (
                    6, 'Domenica'), (5, 'Sabato'), (2, 'Mercoledi')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Giovedi'), (
                4, 'Venerdi'), (1, 'Martedi'), (0, 'Lunedi'), (
                    6, 'Domenica'), (5, 'Sabato'), (2, 'Mercoledi')]),
        ),
    ]
