# Generated by Django 5.2 on 2025-05-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0017_alter_hours_weekday_alter_menu_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Giovedi'), (
                2, 'Mercoledi'), (1, 'Martedi'), (6, 'Domenica'), (
                    4, 'Venerdi'), (5, 'Sabato'), (0, 'Lunedi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(
                3, 'Dessert/Frutta'), (0,
                                       'Primo'), (2,
                                                  'Contorno'), (1,
                                                                'Secondo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(3, 'Giovedi'), (
                2, 'Mercoledi'), (1, 'Martedi'), (6, 'Domenica'), (
                    4, 'Venerdi'), (5, 'Sabato'), (0, 'Lunedi')]),
        ),
    ]
