# Generated by Django 5.2.1 on 2025-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0017_alter_hours_weekday_alter_includes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(4, 'Venerdi'), (5, 'Sabato'), (2, 'Mercoledi'), (6, 'Domenica'), (1, 'Martedi'), (3, 'Giovedi'), (0, 'Lunedi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(2, 'Contorno'), (3, 'Dessert/Frutta'), (1, 'Secondo'), (0, 'Primo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(4, 'Venerdi'), (5, 'Sabato'), (2, 'Mercoledi'), (6, 'Domenica'), (1, 'Martedi'), (3, 'Giovedi'), (0, 'Lunedi')]),
        ),
    ]
