# Generated by Django 5.2 on 2025-05-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0018_alter_hours_weekday_alter_includes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(2, 'Mercoledi'), (6, 'Domenica'), (5, 'Sabato'), (3, 'Giovedi'), (1, 'Martedi'), (0, 'Lunedi'), (4, 'Venerdi')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(1, 'Secondo'), (2, 'Contorno'), (3, 'Dessert/Frutta'), (0, 'Primo')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(2, 'Mercoledi'), (6, 'Domenica'), (5, 'Sabato'), (3, 'Giovedi'), (1, 'Martedi'), (0, 'Lunedi'), (4, 'Venerdi')]),
        ),
    ]
