# Generated by Django 5.2 on 2025-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0019_alter_hours_weekday_alter_includes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='daypart',
            field=models.IntegerField(choices=[(0, 'Pranzo'), (1, 'Cena')]),
        ),
        migrations.AlterField(
            model_name='hours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lunedi'), (1, 'Martedi'), (2, 'Mercoledi'), (3, 'Giovedi'), (4, 'Venerdi'), (5, 'Sabato'), (6, 'Domenica')]),
        ),
        migrations.AlterField(
            model_name='includes',
            name='type',
            field=models.IntegerField(choices=[(0, 'Primo'), (1, 'Secondo'), (2, 'Contorno'), (3, 'Dessert/Frutta')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day_part',
            field=models.IntegerField(choices=[(0, 'Pranzo'), (1, 'Cena')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lunedi'), (1, 'Martedi'), (2, 'Mercoledi'), (3, 'Giovedi'), (4, 'Venerdi'), (5, 'Sabato'), (6, 'Domenica')]),
        ),
    ]
