# Generated by Django 5.2 on 2025-05-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensa', '0017_alter_hours_weekday_alter_includes_type_and_more'),
        ('mensa', '0020_alter_hours_daypart_alter_hours_weekday_and_more'),
    ]

    operations = [
    ]
